# Generated by Django 4.1.1 on 2022-11-27 16:24

import backend.api.models.submodels.feedback
import backend.api.models.submodels.grading
import backend.api.models.submodels.types
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="The quiz author's first name.", max_length=50
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True,
                        help_text="The quiz author's last name.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "pseudo",
                    models.CharField(
                        blank=True,
                        help_text="A pseudo for the quiz author.",
                        max_length=12,
                        null=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="The quiz author's email.", max_length=254
                    ),
                ),
            ],
            options={
                "verbose_name_plural": " Authors",
            },
        ),
        migrations.CreateModel(
            name="ChoiceQuestionOption",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False,
                        help_text="The Id of the option.",
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "display",
                    models.TextField(
                        help_text="The actual display of the option as a human-readable string."
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "   Choice question options",
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "_id",
                    djongo.models.fields.ObjectIdField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True,
                        help_text="General feedback/explanation displayed whether the answer is wrong or correct.",
                        null=True,
                    ),
                ),
                (
                    "when_wrong",
                    models.TextField(
                        blank=True,
                        help_text="Feedback when answer is wrong.",
                        null=True,
                    ),
                ),
                (
                    "when_right",
                    models.TextField(
                        blank=True,
                        help_text="Feedback when answer is right.",
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "_id",
                    djongo.models.fields.ObjectIdField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("TXT", ".txt"),
                            ("CSV", ".csv"),
                            ("PDF", ".pdf"),
                            ("IMG", ".img"),
                            ("PNG", ".png"),
                            ("JPG", ".jpg"),
                            ("JPEG", ".jpeg"),
                        ],
                        default="TXT",
                        help_text="The file type.",
                        max_length=10,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Encoded `base64` string of the file's content."
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Grading",
            fields=[
                (
                    "_id",
                    djongo.models.fields.ObjectIdField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                (
                    "point_value",
                    models.IntegerField(
                        help_text="Specifies how much a correct answer count for in the total score."
                    ),
                ),
                (
                    "feedback",
                    djongo.models.fields.EmbeddedField(
                        help_text="Feedback given after answering the question.",
                        model_container=backend.api.models.submodels.feedback.Feedback,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OptionId",
            fields=[
                (
                    "_id",
                    djongo.models.fields.ObjectIdField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="The Id of an existing Question Option object.",
                        max_length=12,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuestionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_id",
                    models.CharField(
                        help_text="Id of a question referenced in the quiz.",
                        max_length=12,
                    ),
                ),
                (
                    "next_question_id",
                    models.CharField(
                        blank=True,
                        help_text="Id of the next question in the quiz chronology. (Keep empty if None)",
                        max_length=12,
                        null=True,
                    ),
                ),
                (
                    "prev_question_id",
                    models.CharField(
                        blank=True,
                        help_text="Id of the previous question in the quiz chronology. (Keep empty if None)",
                        max_length=12,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "  Question items",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The tag name or label.", max_length=12, unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False,
                        help_text="Id of the quiz.",
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The title (header) of the quiz.",
                        max_length=40,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="A brief description of the quiz content, topic..."
                    ),
                ),
                (
                    "max_score",
                    models.IntegerField(
                        default=0, help_text="Maximum score the user can get."
                    ),
                ),
                (
                    "authors",
                    djongo.models.fields.ArrayReferenceField(
                        blank=True,
                        help_text="List of optional authors or contributors of the quiz.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.author",
                    ),
                ),
                (
                    "questions",
                    models.ManyToManyField(
                        help_text="All the questions the quiz is made of.",
                        to="api.questionitem",
                    ),
                ),
                (
                    "tags",
                    djongo.models.fields.ArrayReferenceField(
                        blank=True,
                        help_text="List of optional tags associated with the quiz.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.tag",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "      Quizzes",
            },
        ),
        migrations.CreateModel(
            name="QuestionSpec",
            fields=[
                (
                    "_id",
                    djongo.models.fields.ObjectIdField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                (
                    "answer_id",
                    djongo.models.fields.EmbeddedField(
                        blank=True,
                        help_text="Id of the correct answer to the question (if single choice).",
                        model_container=backend.api.models.submodels.types.OptionId,
                        null=True,
                    ),
                ),
                (
                    "answers_id",
                    djongo.models.fields.ArrayField(
                        blank=True,
                        help_text="Id of the correct answers to the question (if multiple choices).",
                        model_container=backend.api.models.submodels.types.OptionId,
                        null=True,
                    ),
                ),
                (
                    "keywords",
                    models.TextField(
                        blank=True,
                        help_text="List of keywords that the answers should contain.",
                        null=True,
                    ),
                ),
                (
                    "max_size",
                    models.CharField(
                        blank=True,
                        help_text="Maximum size of each files. Can be expressed in bytes, megabytes (MB), etc.",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "max_files",
                    models.IntegerField(
                        blank=True,
                        default=1,
                        help_text="Maximum number of files to upload.",
                        null=True,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="Code content. This will be run using a `python3` runner and evaluated.",
                        null=True,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        default="python3",
                        help_text="Coding language. Only `python3` is supported.",
                        max_length=25,
                        null=True,
                    ),
                ),
                (
                    "expected_output",
                    models.TextField(
                        blank=True,
                        help_text="Expected output after running the code.",
                        null=True,
                    ),
                ),
                (
                    "files",
                    djongo.models.fields.ArrayReferenceField(
                        blank=True,
                        help_text="List of files to upload.",
                        null=True,
                        on_delete=djongo.models.fields.ArrayReferenceField._on_delete,
                        to="api.file",
                    ),
                ),
                (
                    "options",
                    djongo.models.fields.ArrayReferenceField(
                        blank=True,
                        help_text="The question options.",
                        null=True,
                        on_delete=djongo.models.fields.ArrayReferenceField._on_delete,
                        to="api.choicequestionoption",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "    Question specs",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False,
                        help_text="Id of the question.",
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "question",
                    models.CharField(
                        help_text="The actual question as a human-readable string.",
                        max_length=500,
                        unique=True,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("EASY", "Easy"),
                            ("MEDIUM", "Medium"),
                            ("HARD", "Hard"),
                        ],
                        default="EASY",
                        help_text="Rate how difficult the question is.",
                        max_length=10,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("CHOICE_QUESTION", "Choice Question"),
                            ("TEXT_QUESTION", "Text Question"),
                            ("UPLOAD_QUESTION", "Upload Question"),
                            ("CODE_QUESTION", "Code Question"),
                        ],
                        default="CHOICE_QUESTION",
                        help_text="The question kind.",
                        max_length=25,
                    ),
                ),
                (
                    "grading",
                    djongo.models.fields.EmbeddedField(
                        help_text="Specifies how to grade for the current question.",
                        model_container=backend.api.models.submodels.grading.Grading,
                    ),
                ),
                (
                    "hint",
                    models.CharField(
                        blank=True,
                        help_text="Hint given to help answering the question.",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "spec",
                    models.OneToOneField(
                        help_text="Spec of the question. It specifies what the attributes of the question are.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.questionspec",
                    ),
                ),
                (
                    "tags",
                    djongo.models.fields.ArrayReferenceField(
                        blank=True,
                        help_text="List of optional tags associated with the question.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.tag",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "     Questions",
            },
        ),
    ]
