name: Lint
on: [pull_request]
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      working-directory: ./frontend
      run: yarn
    - name: Run ESLint
      working-directory: ./frontend
      run: yarn eslint src/
  pycodestyle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup virtual environment
      working-directory: ./backend
      run: make venv
    - name: Activate virtual environment
      working-directory: ./backend
      run: source venv/bin/activate
    - name: Run pycodestyle
      working-directory: ./backend
      run: make lint